/**
 * Wire protocol for Cloud Mesh peer connections.
 *
 * All peer-to-peer traffic over the mesh transport (Trystero room
 * action channel; previously a PeerJS DataConnection — the protocol
 * is transport-agnostic) is framed as JSON messages with a
 * discriminated `kind` field. The two
 * pre-active phases are:
 *
 *   1. `hello` — each side announces its claimed Device ID and a
 *      random nonce. Sent immediately on channel open.
 *   2. `auth_response` — each side returns the other's nonce signed
 *      with its own private key. Receiving a valid signature
 *      authenticates that the sender owns the keypair matching its
 *      claimed Device ID.
 *
 * After mutual auth-response verification, the receiver side either
 * auto-accepts (if the peer is in the roster) or queues the request
 * for user approval. The receiver sends `approve` once cleared; the
 * connection becomes ACTIVE on both sides at that point.
 *
 * Domain separation: every signed payload is prefixed with the tag
 * below so a signature obtained for one protocol step can't be
 * replayed in another.
 */

import { invoke } from "@tauri-apps/api/core";

export const PROTOCOL_VERSION = 1;
export const SIGN_DOMAIN_TAG = "myownllm-mesh-auth-v1:";

export type MeshMessage =
  | HelloMessage
  | AuthResponseMessage
  | ApproveMessage
  | DenyMessage
  | PingMessage
  | PongMessage
  | CatalogAnnounceMessage
  | MoveOfferMessage
  | MoveAcceptMessage
  | MoveDeclineMessage
  | MovePayloadMessage
  | MoveCompleteMessage;

export interface HelloMessage {
  kind: "hello";
  protocol: number;
  /** Bare-pubkey Device ID, base32-lowercase. Display suffix omitted
   *  on the wire — the receiver derives it themselves if they want
   *  to show the peer to the user. */
  device_id: string;
  /** Self-reported label. Cosmetic; peers cannot rely on labels for
   *  identity. */
  label: string;
  /** Random 32-byte challenge, base32-lowercase. The other side
   *  must sign `SIGN_DOMAIN_TAG || nonce || my_device_id || their_device_id`
   *  and return the signature in `auth_response`. */
  nonce: string;
  /** Short human-readable verification code (6 chars, `[a-z0-9]`)
   *  generated by the sender. Displayed prominently on both sides
   *  during a pending approval so the users can confirm by
   *  out-of-band channel ("hey I'm sending a request, my code is
   *  X") that the request they see is really from the person they
   *  think it is. Not load-bearing — the ed25519 signatures
   *  authenticate identity; this is just a UX confirmation. */
  verification_code: string;
}

export interface AuthResponseMessage {
  kind: "auth_response";
  /** Base32-lowercase signature of the peer's nonce framed under the
   *  domain tag. */
  signature: string;
}

export interface ApproveMessage {
  kind: "approve";
}

export interface DenyMessage {
  kind: "deny";
  reason?: string;
}

export interface PingMessage {
  kind: "ping";
  /** Sender's monotonic timestamp; echoed back in `pong` so the
   *  receiver can compute round-trip latency. */
  t: number;
}

export interface PongMessage {
  kind: "pong";
  t: number;
}

// ---- catalog + move -----------------------------------------------------

/** Lightweight metadata for a conversation hosted on the announcer.
 *  Catalog entries propagate freely between peers so any peer can
 *  render a list of "what's where" without forcing content
 *  replication. The hosting peer is whoever sent the announcement. */
export interface CatalogEntry {
  guid: string;
  title: string;
  mode: string;
  updated_at: string;
}

export interface CatalogAnnounceMessage {
  kind: "catalog_announce";
  /** Replaces the announcer's previous catalog wholesale rather
   *  than mutating per-entry. v1 catalogs are small (hundreds of
   *  entries), so the simplicity-vs-bandwidth trade is the right
   *  call. Incremental gossip can land alongside the OR-set
   *  roster when we add that. */
  conversations: CatalogEntry[];
}

/** Initiator offers a Move of conversation `guid` to the recipient.
 *  Includes the title so the receiver can show a friendlier "X is
 *  about to send you 'Standup notes'" if we later add an opt-in
 *  confirmation prompt. */
export interface MoveOfferMessage {
  kind: "move_offer";
  guid: string;
  title: string;
}

export interface MoveAcceptMessage {
  kind: "move_accept";
  guid: string;
}

export interface MoveDeclineMessage {
  kind: "move_decline";
  guid: string;
  reason: string;
}

/** The full conversation payload, sent as a JSON-encoded object. The
 *  receiver writes it to local storage before sending `move_complete`,
 *  at which point the initiator deletes its local copy. */
export interface MovePayloadMessage {
  kind: "move_payload";
  guid: string;
  conversation: unknown;
}

export interface MoveCompleteMessage {
  kind: "move_complete";
  guid: string;
}

/** Compose the payload that a peer signs in response to a `hello`.
 *  Both sides assemble the same bytes from the message contents so
 *  what's signed on one end is exactly what's verified on the other.
 *  We base32-encode the resulting bytes for the Tauri bridge. */
export function authPayload(opts: {
  nonce: string;
  my_device_id: string;
  their_device_id: string;
}): string {
  const text = `${SIGN_DOMAIN_TAG}${opts.nonce}|${opts.my_device_id}|${opts.their_device_id}`;
  // Encode as base32 nopad lowercase — matches what `mesh_sign` and
  // `mesh_verify` accept on the Rust side.
  const bytes = new TextEncoder().encode(text);
  return base32Encode(bytes);
}

/** Generate a random nonce as base32-lowercase. 32 bytes = 52 chars,
 *  same encoding the rest of the mesh uses. */
export function generateNonce(): string {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  return base32Encode(bytes);
}

/** Derive the 5-char uppercase-hex display suffix from a peer's
 *  base32 pubkey string. Mirrors the Rust `display_suffix` exactly
 *  (sha256 of the string bytes → first 5 hex chars, uppercased) so
 *  the same device shows the same tail in our UI as it does in its
 *  own. Async because SubtleCrypto.digest is. */
export async function pubkeySuffix(pubkey: string): Promise<string> {
  const bytes = new TextEncoder().encode(pubkey);
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  const view = new Uint8Array(digest);
  let hex = "";
  for (let i = 0; i < 3 && hex.length < 5; i++) {
    hex += view[i].toString(16).padStart(2, "0").toUpperCase();
  }
  return hex.slice(0, 5);
}

/** Generate a short human-readable verification code. 6 chars from
 *  `[a-z0-9]` = 36^6 ≈ 2 billion possibilities — vastly more than
 *  needed for a "did the right request just arrive?" eyeball check,
 *  and short enough to read over a phone call. */
export function generateVerificationCode(): string {
  const ALPHABET = "abcdefghijklmnopqrstuvwxyz0123456789";
  const bytes = new Uint8Array(6);
  crypto.getRandomValues(bytes);
  let out = "";
  for (const b of bytes) out += ALPHABET[b % ALPHABET.length];
  return out;
}

/** Sign a base32-encoded message via the Rust signing command.
 *  Trampolines through Tauri so the private key never leaves the
 *  anchor file. */
export async function signMessage(message_b32: string): Promise<string> {
  return await invoke<string>("mesh_sign", { messageB32: message_b32 });
}

/** Verify a peer's claimed signature. Returns true iff valid. */
export async function verifySignature(
  device_id: string,
  message_b32: string,
  signature_b32: string,
): Promise<boolean> {
  return await invoke<boolean>("mesh_verify", {
    deviceId: device_id,
    messageB32: message_b32,
    signatureB32: signature_b32,
  });
}

// ---- base32 encoding ----------------------------------------------------
//
// RFC 4648 base32, lowercase, no padding. The same encoding the Rust
// side uses via `data_encoding::BASE32_NOPAD` (lowercased). Keeping
// a hand-rolled encoder here so we don't pull in another runtime
// dependency just for this; the algorithm is simple.

const BASE32_ALPHABET = "abcdefghijklmnopqrstuvwxyz234567";

export function base32Encode(bytes: Uint8Array): string {
  let bits = 0;
  let value = 0;
  let out = "";
  for (const b of bytes) {
    value = (value << 8) | b;
    bits += 8;
    while (bits >= 5) {
      out += BASE32_ALPHABET[(value >>> (bits - 5)) & 0x1f];
      bits -= 5;
    }
  }
  if (bits > 0) {
    out += BASE32_ALPHABET[(value << (5 - bits)) & 0x1f];
  }
  return out;
}

/** Strip the `-XXXXX` display suffix from a Device ID, returning
 *  just the pubkey portion. Mirrors `signing::pubkey_part` on the
 *  Rust side. */
export function pubkeyPart(device_id: string): string {
  const idx = device_id.lastIndexOf("-");
  if (idx === -1) return device_id;
  const suffix = device_id.slice(idx + 1);
  if (suffix.length === 5 && /^[a-z0-9]+$/.test(suffix)) {
    return device_id.slice(0, idx);
  }
  return device_id;
}

/** Derive a Trystero room id from a user-typed Network ID. Hashes
 *  under a domain-separation tag so the same string used elsewhere
 *  can't collide, then base32-encodes to a fixed 52 chars. Trystero
 *  doesn't care about the format, but the hash means two devices
 *  who type the exact same human Network ID end up in the same
 *  room without leaking the user's chosen name to anyone scraping
 *  the underlying signaling substrate (BitTorrent trackers, Nostr
 *  relays, etc.). Async because SubtleCrypto is — callers cache
 *  the result for the session. */
export async function deriveNetworkHandle(network_id: string): Promise<string> {
  const tagged = `myownllm-network-v1:${network_id}`;
  const bytes = new TextEncoder().encode(tagged);
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return base32Encode(new Uint8Array(digest));
}
